### ISSUE TITLE
Errors when trying to rebuild

### ISSUE THREAD

**Issue by harunnoir** [ptdewey/pendulum-nvim#6]
When running PendulumRebuild I'm getting the following errors

![image](https://github.com/user-attachments/assets/aaf2a35c-6ec3-41a9-b19c-c7bee670cab7)

**Comment by ptdewey** [comment]
Can you send your plugin config and what os you are using?

**Comment by harunnoir** [comment]
> Can you send your plugin config and what os you are using?

configs:
![image](https://github.com/user-attachments/assets/d5c83178-9214-4de4-8798-1abc8d4a7957)

OS: Arch linux

**Comment by ptdewey** [comment]
So this problem is arising partially because of your config and partially because of a mistake I made in the user command creation. 
First, in order to use the report generation (Pendulum and PendulumRebuild commands), you need to specifically set the `gen_reports=true` option in your config as it is disabled by default.

See example config from README.md: (You'll need to translate it to fennel yourself)
```lua
require('pendulum').setup({
    log_file = vim.fn.expand("$HOME/Documents/my_custom_log.csv"),
    timeout_len = 300,  -- 5 minutes
    timer_len = 60,     -- 1 minute
    gen_reports = true, -- Enable report generation (requires Go)
    top_n = 10,         -- Include top 10 entries in the report
})
```

Secondly, your issue arose because the two user commands were created regardless of the value of gen_reports, when they should only have been created when the option is specifically enabled. I have since fixed this in the most recent version.
