### ISSUE TITLE
Empty setup causes the module not to load

### ISSUE THREAD

**Issue by ijakenorton** [ptdewey/pendulum-nvim#8]
When using lazy, the default config with 
return {
	"ptdewey/pendulum-nvim",
	config = function()
		require("pendulum").setup()
	end,
}
Does not load properly, the Pendulum and PendulumRebuild commands do not work. However adding an empty table or using the config such as 
return {
	"ptdewey/pendulum-nvim",
	config = function()
		require("pendulum").setup({
			log_file = vim.fn.expand("$HOME/Documents/my_custom_log.csv"),
			timeout_len = 300, -- 5 minutes
			timer_len = 60, -- 1 minute
			gen_reports = true, -- Enable report generation (requires Go)
			top_n = 10, -- Include top 10 entries in the report
		})
	end,
}
Does load properly
Could be some issue due to my system, or passing a nil value to the setup function is not handled

**Comment by ptdewey** [comment]
@ijakenorton The commands not being available with an empty/default config is actually by design, as I originally designed the plugin with only the CSV logging capabilities (no popup reports), and I didn't want to mandate the Go dependency that the popup generation requires. 
I thought I mentioned that in the README in the report section, but after taking a glance at it I realized I never actually explicitly mentioned that a setting needs to be enabled for it. 

Overall, I suspect most people interested in this plugin are interested in the time report generation feature, so I'll probably change the default setting to be opt-out rather than opt-in for them. I'll also update the README to make things more clear.

**Comment by ijakenorton** [comment]
Nice cheers mate!
